### PR TITLE
Improve Codespaces Setup

### PR DESCRIPTION
**Pull request by davidkopp**
- Fix runner command for example application in quickstart
- Add VS Code extensions
- Open markdown files in preview mode by default
- Ensure ports are set to public after Codespace restart
- Ignore backuped Makefile in Git
- Improve quickstart and add troubleshooting information

### CODE REVIEW

**Comment by ArneTR** [comment]
Please request a review once you feel this is ready to merge. I saw some commits dropping in over the last days. Happy to keep it open for a while until you feel it's ready

**Comment by ArneTR** [comment]
I updated the base codespaces branch. The diff is now more compact

**Comment by davidkopp** [comment]
> Please request a review once you feel this is ready to merge. I saw some commits dropping in over the last days. Happy to keep it open for a while until you feel it's ready

Ok, I will let you know, when I'm sure that there won't be any more improvements from my side.

**Comment by ArneTR** [comment]
@davidkopp Wanted to check in if you have any status updates on this

**Comment by davidkopp** [comment]
I will continue working on the Codespace setup in September. So if it's ok for you, you can leave the PR open. It would be also ok for if you merge it now I can create another PR if needed.

**Comment by davidkopp** [comment]
Sorry for the delay! This week I finally had the first workshop using this setup. It worked great!
From my point of view the PR can now be merged.

The branch doesn't include the latest changes in main since July. To merge them some conflicts have to be solved. Because I was not sure how to solve the conflicts of the cgroup metric providers, I haven't done the merge yet.

**Comment by ArneTR** [comment]
LGTM! I will update the codespaces branch separatetly

**Pull request merged**
