### PR TITLE
Fixes wrong o vs. O parameter

### PR DESCRIPTION
**Pull request by ribalba**
-o is for output file -O is for optimisations

### CODE REVIEW

**Comment by ArneTR** [comment]
Interesting. Your code still has a ZERO (0) instead of a big O, so this is why it fails.

On a test I see sadly zero improvement. With 14k the binary is already as small as it get's it seems

**Comment by ribalba** [comment]
But is binary size really and indication of performance? Couldn't the binary be the same size but use far better CPU optimisations? Or the binary could even be bigger but faster in execution if some debug symbols are left out but a simple loop is flattened.

**Comment by ArneTR** [comment]
If you want to go wild about it maybe. Actually if I compare not in the kB dimension but in Bytes the O3 is *bigger* than the O2.
What happens internally is hard to say as the load of the code is already close to unmeasureable. I love the optimization, but I believe it is largely irrelevant in a bigger picture given we are already below our planned thresshold of being < 1% CPU utilization per reporter.

**Comment by ArneTR** [comment]
Merging in as only a fronted test flakes. Will monitor if this happens more often. Seems like a race condition

**Pull request merged**
